package uk.ac.sheffield.com2008.navigation;


public enum Navigation {

    SIGNUP, LOGIN, CUSTOMER, STAFF, MANAGER, PRODUCT_RECORD, PRODUCTFORM, BASKET, ORDER_HISTORY, MANAGE_ORDER, SALES, EDIT_PRODUCT_RECORD, FULFILLED_ORDERS, MANAGE_PROFILE, PROVIDE_ADDRESS, ORDER_LIST


}
