package uk.ac.sheffield.com2008.navigation;


public enum Navigation {

    SIGNUP, LOGIN, CUSTOMER, STAFF, MANAGER, PRODUCTRECORD, PRODUCTFORM, BASKET, ORDER_HISTORY, MANAGE_ORDER, SALES, ORDER_LIST

}
